services:
  z1_controller:
    build: ../z1_controller/
    privileged: true
    network_mode: "host" 
    ipc: "host"
    stop_grace_period: 40s
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related   
    command: /bin/bash  

  sas_unitree_z1_control_template:
    build: ../sas_unitree_z1_control_template
    privileged: true
    network_mode: "host" 
    ipc: "host"
    stop_signal: SIGINT
    stop_grace_period: 30s
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related  
    command: /bin/bash -c "
      export ROS_DOMAIN_ID=1;
      cd /root/git/sas_unitree_z1_control_template/devel/scripts/
      && chmod +x build_packages.sh && chmod +x countdown.sh
      && . /root/git/sas_unitree_z1_control_template/devel/scripts/build_packages.sh
      && ros2 launch sas_robot_driver_unitree_z1 real_z1_robot_launch.py "


# && . /root/git/sas_robot_driver_unitree_z1/dependencies/countdown.sh 10 

    #command: /bin/bash -c "
    #  source /opt/ros/jazzy/setup.bash;
    #  export ROS_DOMAIN_ID=1;
    #  cd ~/ros2_ws/ && colcon build;
    #  source ~/ros2_ws/install/setup.bash;
    #  sleep 4;
    #  ros2 launch sas_robot_driver_unitree_z1 real_z1_robot_launch.py "