services:
  sas_unitree_z1_control_template:
    build: ../sas_unitree_z1_control_template
    privileged: true
    network_mode: "host" 
    ipc: "host"
    stop_signal: SIGINT
    stop_grace_period: 30s
    environment:
      DISPLAY: $DISPLAY
    #volumes:
    #  - sas-unitree-z1-control-control-template-repo-data:/root/ros2_ws/src/sas_unitree_z1_control_template/
    command: /bin/bash -c "
      export ROS_DOMAIN_ID=1;
      cd /root/ros2_ws/src/sas_unitree_z1_control_template/devel/scripts/
      && chmod +x build_packages.sh;
      . /root/ros2_ws/src/sas_unitree_z1_control_template/devel/scripts/build_packages.sh;
      ros2 launch sas_unitree_z1_control_template simulation_example_cpp_launch.py  coppeliasim_timeout:=10000"



